### ISSUE TITLE
Error with reports with focused or disabled tests

### ISSUE THREAD

**Issue by ldeveber** [stuisme/protractor-pretty-html-reporter#9]
Protractor is failing with the following when a test is disabled or focused:
```
[2018-01-25 13:07:34.138] [ERROR] - TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at Reporter.writeImage (/Users/xxx/projects/yy-static/protractor/node_modules/protractor-pretty-html-reporter/reporter.js:169:22)
    at Reporter.specDone (/Users/xxx/projects/yy-static/protractor/node_modules/protractor-pretty-html-reporter/reporter.js:117:18)
    at dispatch (/Users/xxx/projects/yy-static/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4522:28)
    at ReportDispatcher.specDone (/Users/xxx/projects/yy-static/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4493:11)
    at Spec.specResultCallback [as resultCallback] (/Users/xxx/projects/yy-static/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1220:18)
    at complete (/Users/xxx/projects/yy-static/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:565:12)
    at QueueRunner.runnerConfig.onComplete (/Users/xxx/projects/yy-static/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:558:46)
    at Immediate._onImmediate (/Users/xxx/projects/yy-static/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4382:12)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

I'm using jasmine 2.9 with protractor 5.2.2.

**Comment by cpaika** [comment]
+1

**Comment by AlexMarchini** [comment]
+1

**Comment by JustMcAfee** [comment]
👍

**Comment by stuisme** [comment]
It looks like it's related to the screenshot functionality.

What browser versions are being used?

**Comment by ldeveber** [comment]
I'm using Chrome, not headless when these errors are appearing.

**Comment by rakeshrk21** [comment]
did we figure out a resolution to this?

**Comment by cpaika** [comment]
@ldeveber Would possibly remember the fix, but we did end up fixing it on our end.  It was a long time ago so I forgot the specific fix unfortunately 😞

**Comment by ldeveber** [comment]
I unfortunately do not remember what I did without looking at the code, which I no longer have access to :(
